'use strict';

var dom;
let sDetail = {}

// css
let s0 = "<span class='",
	sb = s0+"bad'>",
	sg = s0+"good'>",
	sf = s0+"faint'>",
	sn = s0+"neutral'>",
	snc = s0+"no_color'>",
	s1 = s0+"s1'>",
	s2 = s0+"s2'>",
	s3 = s0+"s3'>",
	s4 = s0+"s4'>",
	s5 = s0+"s5'>",
	s6 = s0+"s6'>",
	s7 = s0+"s7'>",
	s8 = s0+"s8'>",
	s9 = s0+"s9'>",
	s10 = s0+"s10'>",
	s11 = s0+"s11'>",
	s12 = s0+"s12'>",
	s13 = s0+"s13'>",
	s14 = s0+"s14'>",
	s15 = s0+"s15'>",
	s16 = s0+"s16'>",
	s17 = s0+"s17'>",
	s18 = s0+"s18'>",
	s99 = s0+"s99'>",
	sc = "</span>",
// test icons
	green_tick = "<span style='font-size: 10px;'><b>" + s9.trim() +" \u2713"+ sc + "</b></span>",
	red_cross = "<span style='font-size: 10px;'><b>" + sb.trim() +" \u2715"+ sc + "</b></span>",
	yellow_block = "<span style='font-size: 10px;'><b>" + s4.trim() +" \u2715"+ sc + "</b></span>",
	white_na =  "<span style='font-size: 10px;'><b>" + snc.trim() +" \u2715"+ sc + "</b></span>",
// common results
	zErr = 'error',
	zNA = 'n/a',
	zU = 'undefined',
	zUQ = "\"undefined\"",
	zNEW = sb+'[NEW]'+sc,
// other
	is95 = false,
	isEngine = '',
	isEnginePretty = '', // results string with perf
	isFF = false,
	isFFpretty = '', // results string with perf
	isFFvalid = false, // no errors
	isFile = false,
	isVer = '',
	isVerMax = ''

// timezones
let gTimezones = [
// no regional prefix
'CET','CST6CDT','Cuba','EET','EST','EST5EDT','Egypt','Eire','Factory','GB','GB-Eire','GMT','GMT+0','GMT-0','GMT0',
'Greenwich','HST','Hongkong','Iceland','Iran','Israel','Jamaica','Japan','Kwajalein','Libya','MET','MST','MST7MDT',
'NZ','NZ-CHAT','Navajo','PRC','PST8PDT','Poland','Portugal','ROC','ROK','Singapore','Turkey','UCT','UTC','Universal',
'W-SU','WET','Zulu',

// THE REST
'Africa/Abidjan','Africa/Accra','Africa/Addis_Ababa','Africa/Algiers','Africa/Asmara','Africa/Asmera','Africa/Bamako',
'Africa/Bangui','Africa/Banjul','Africa/Bissau','Africa/Blantyre','Africa/Brazzaville','Africa/Bujumbura','Africa/Cairo',
'Africa/Casablanca','Africa/Ceuta','Africa/Conakry','Africa/Dakar','Africa/Dar_es_Salaam','Africa/Djibouti','Africa/Douala',
'Africa/El_Aaiun','Africa/Freetown','Africa/Gaborone','Africa/Harare','Africa/Johannesburg','Africa/Juba','Africa/Kampala',
'Africa/Khartoum','Africa/Kigali','Africa/Kinshasa','Africa/Lagos','Africa/Libreville','Africa/Lome','Africa/Luanda',
'Africa/Lubumbashi','Africa/Lusaka','Africa/Malabo','Africa/Maputo','Africa/Maseru','Africa/Mbabane','Africa/Mogadishu',
'Africa/Monrovia','Africa/Nairobi','Africa/Ndjamena','Africa/Niamey','Africa/Nouakchott','Africa/Ouagadougou',
'Africa/Porto-Novo','Africa/Sao_Tome','Africa/Timbuktu','Africa/Tripoli','Africa/Tunis','Africa/Windhoek',

'America/Adak','America/Anchorage','America/Anguilla','America/Antigua','America/Araguaina','America/Argentina/Buenos_Aires',
'America/Argentina/Catamarca','America/Argentina/ComodRivadavia','America/Argentina/Cordoba','America/Argentina/Jujuy',
'America/Argentina/La_Rioja','America/Argentina/Mendoza','America/Argentina/Rio_Gallegos','America/Argentina/Salta',
'America/Argentina/San_Juan','America/Argentina/San_Luis','America/Argentina/Tucuman','America/Argentina/Ushuaia',
'America/Aruba','America/Asuncion','America/Atikokan','America/Atka','America/Bahia','America/Bahia_Banderas',
'America/Barbados','America/Belem','America/Belize','America/Blanc-Sablon','America/Boa_Vista','America/Bogota',
'America/Boise','America/Buenos_Aires','America/Cambridge_Bay','America/Campo_Grande','America/Cancun','America/Caracas',
'America/Catamarca','America/Cayenne','America/Cayman','America/Chicago','America/Chihuahua','America/Ciudad_Juarez',
'America/Coral_Harbour','America/Cordoba','America/Costa_Rica','America/Creston','America/Cuiaba','America/Curacao',
'America/Danmarkshavn','America/Dawson','America/Dawson_Creek','America/Denver','America/Detroit','America/Dominica',
'America/Edmonton','America/Eirunepe','America/El_Salvador','America/Ensenada','America/Fort_Nelson','America/Fort_Wayne',
'America/Fortaleza','America/Glace_Bay','America/Godthab','America/Goose_Bay','America/Grand_Turk','America/Grenada',
'America/Guadeloupe','America/Guatemala','America/Guayaquil','America/Guyana','America/Halifax','America/Havana',
'America/Hermosillo','America/Indiana/Indianapolis','America/Indiana/Knox','America/Indiana/Marengo',
'America/Indiana/Petersburg','America/Indiana/Tell_City','America/Indiana/Vevay','America/Indiana/Vincennes',
'America/Indiana/Winamac','America/Indianapolis','America/Inuvik','America/Iqaluit','America/Jamaica','America/Jujuy',
'America/Juneau','America/Kentucky/Louisville','America/Kentucky/Monticello','America/Knox_IN','America/Kralendijk',
'America/La_Paz','America/Lima','America/Los_Angeles','America/Louisville','America/Lower_Princes','America/Maceio',
'America/Managua','America/Manaus','America/Marigot','America/Martinique','America/Matamoros','America/Mazatlan',
'America/Mendoza','America/Menominee','America/Merida','America/Metlakatla','America/Mexico_City','America/Miquelon',
'America/Moncton','America/Monterrey','America/Montevideo','America/Montreal','America/Montserrat','America/Nassau',
'America/New_York','America/Nipigon','America/Nome','America/Noronha','America/North_Dakota/Beulah',
'America/North_Dakota/Center','America/North_Dakota/New_Salem','America/Nuuk','America/Ojinaga','America/Panama',
'America/Pangnirtung','America/Paramaribo','America/Phoenix','America/Port-au-Prince','America/Port_of_Spain',
'America/Porto_Acre','America/Porto_Velho','America/Puerto_Rico','America/Punta_Arenas','America/Rainy_River',
'America/Rankin_Inlet','America/Recife','America/Regina','America/Resolute','America/Rio_Branco','America/Rosario',
'America/Santa_Isabel','America/Santarem','America/Santiago','America/Santo_Domingo','America/Sao_Paulo',
'America/Scoresbysund','America/Shiprock','America/Sitka','America/St_Barthelemy','America/St_Johns','America/St_Kitts',
'America/St_Lucia','America/St_Thomas','America/St_Vincent','America/Swift_Current','America/Tegucigalpa',
'America/Thule','America/Thunder_Bay','America/Tijuana','America/Toronto','America/Tortola','America/Vancouver',
'America/Virgin','America/Whitehorse','America/Winnipeg','America/Yakutat','America/Yellowknife',
'America/Coyhaique', // tzdata2025b

'Antarctica/Casey','Antarctica/Davis','Antarctica/DumontDUrville','Antarctica/Macquarie','Antarctica/Mawson',
'Antarctica/McMurdo','Antarctica/Palmer','Antarctica/Rothera','Antarctica/South_Pole','Antarctica/Syowa',
'Antarctica/Troll','Antarctica/Vostok','Arctic/Longyearbyen',

'Asia/Aden','Asia/Almaty','Asia/Amman','Asia/Anadyr','Asia/Aqtau','Asia/Aqtobe','Asia/Ashgabat','Asia/Ashkhabad',
'Asia/Atyrau','Asia/Baghdad','Asia/Bahrain','Asia/Baku','Asia/Bangkok','Asia/Barnaul','Asia/Beirut','Asia/Bishkek',
'Asia/Brunei','Asia/Calcutta','Asia/Chita','Asia/Choibalsan','Asia/Chongqing','Asia/Chungking','Asia/Colombo',
'Asia/Dacca','Asia/Damascus','Asia/Dhaka','Asia/Dili','Asia/Dubai','Asia/Dushanbe','Asia/Famagusta','Asia/Gaza',
'Asia/Harbin','Asia/Hebron','Asia/Ho_Chi_Minh','Asia/Hong_Kong','Asia/Hovd','Asia/Irkutsk','Asia/Istanbul',
'Asia/Jakarta','Asia/Jayapura','Asia/Jerusalem','Asia/Kabul','Asia/Kamchatka','Asia/Karachi','Asia/Kashgar',
'Asia/Kathmandu','Asia/Katmandu','Asia/Khandyga','Asia/Kolkata','Asia/Krasnoyarsk','Asia/Kuala_Lumpur','Asia/Kuching',
'Asia/Kuwait','Asia/Macao','Asia/Macau','Asia/Magadan','Asia/Makassar','Asia/Manila','Asia/Muscat','Asia/Nicosia',
'Asia/Novokuznetsk','Asia/Novosibirsk','Asia/Omsk','Asia/Oral','Asia/Phnom_Penh','Asia/Pontianak','Asia/Pyongyang',
'Asia/Qatar','Asia/Qostanay','Asia/Qyzylorda','Asia/Rangoon','Asia/Riyadh','Asia/Saigon','Asia/Sakhalin',
'Asia/Samarkand','Asia/Seoul','Asia/Shanghai','Asia/Singapore','Asia/Srednekolymsk','Asia/Taipei','Asia/Tashkent',
'Asia/Tbilisi','Asia/Tehran','Asia/Tel_Aviv','Asia/Thimbu','Asia/Thimphu','Asia/Tokyo','Asia/Tomsk','Asia/Ujung_Pandang',
'Asia/Ulaanbaatar','Asia/Ulan_Bator','Asia/Urumqi','Asia/Ust-Nera','Asia/Vientiane','Asia/Vladivostok','Asia/Yakutsk',
'Asia/Yangon','Asia/Yekaterinburg','Asia/Yerevan',

'Atlantic/Azores','Atlantic/Bermuda','Atlantic/Canary','Atlantic/Cape_Verde','Atlantic/Faeroe','Atlantic/Faroe',
'Atlantic/Jan_Mayen','Atlantic/Madeira','Atlantic/Reykjavik','Atlantic/South_Georgia','Atlantic/St_Helena',
'Atlantic/Stanley',

'Australia/ACT','Australia/Adelaide','Australia/Brisbane','Australia/Broken_Hill','Australia/Canberra','Australia/Currie',
'Australia/Darwin','Australia/Eucla','Australia/Hobart','Australia/LHI','Australia/Lindeman','Australia/Lord_Howe',
'Australia/Melbourne','Australia/NSW','Australia/North','Australia/Perth','Australia/Queensland','Australia/South',
'Australia/Sydney','Australia/Tasmania','Australia/Victoria','Australia/West','Australia/Yancowinna',

'Brazil/Acre','Brazil/DeNoronha','Brazil/East','Brazil/West',

'Canada/Atlantic','Canada/Central','Canada/Eastern','Canada/Mountain','Canada/Newfoundland','Canada/Pacific',
'Canada/Saskatchewan','Canada/Yukon',

'Chile/Continental','Chile/EasterIsland',

'Etc/GMT','Etc/GMT+0','Etc/GMT+1','Etc/GMT+10','Etc/GMT+11','Etc/GMT+12','Etc/GMT+2','Etc/GMT+3','Etc/GMT+4',
'Etc/GMT+5','Etc/GMT+6','Etc/GMT+7','Etc/GMT+8','Etc/GMT+9','Etc/GMT-0','Etc/GMT-1','Etc/GMT-10','Etc/GMT-11',
'Etc/GMT-12','Etc/GMT-13','Etc/GMT-14','Etc/GMT-2','Etc/GMT-3','Etc/GMT-4','Etc/GMT-5','Etc/GMT-6','Etc/GMT-7',
'Etc/GMT-8','Etc/GMT-9','Etc/GMT0','Etc/Greenwich','Etc/UCT','Etc/UTC','Etc/Universal','Etc/Zulu',

'Europe/Amsterdam','Europe/Andorra','Europe/Astrakhan','Europe/Athens','Europe/Belfast','Europe/Belgrade','Europe/Berlin',
'Europe/Bratislava','Europe/Brussels','Europe/Bucharest','Europe/Budapest','Europe/Busingen','Europe/Chisinau',
'Europe/Copenhagen','Europe/Dublin','Europe/Gibraltar','Europe/Guernsey','Europe/Helsinki','Europe/Isle_of_Man',
'Europe/Istanbul','Europe/Jersey','Europe/Kaliningrad','Europe/Kiev','Europe/Kirov','Europe/Kyiv','Europe/Lisbon',
'Europe/Ljubljana','Europe/London','Europe/Luxembourg','Europe/Madrid','Europe/Malta','Europe/Mariehamn','Europe/Minsk',
'Europe/Monaco','Europe/Moscow','Europe/Nicosia','Europe/Oslo','Europe/Paris','Europe/Podgorica','Europe/Prague','Europe/Riga',
'Europe/Rome','Europe/Samara','Europe/San_Marino','Europe/Sarajevo','Europe/Saratov','Europe/Simferopol','Europe/Skopje',
'Europe/Sofia','Europe/Stockholm','Europe/Tallinn','Europe/Tirane','Europe/Tiraspol','Europe/Ulyanovsk','Europe/Uzhgorod',
'Europe/Vaduz','Europe/Vatican','Europe/Vienna','Europe/Vilnius','Europe/Volgograd','Europe/Warsaw','Europe/Zagreb',
'Europe/Zaporozhye','Europe/Zurich',

'Indian/Antananarivo','Indian/Chagos','Indian/Christmas','Indian/Cocos','Indian/Comoro','Indian/Kerguelen',
'Indian/Mahe','Indian/Maldives','Indian/Mauritius','Indian/Mayotte','Indian/Reunion',

'Mexico/BajaNorte','Mexico/BajaSur','Mexico/General',

'Pacific/Apia','Pacific/Auckland','Pacific/Bougainville','Pacific/Chatham','Pacific/Chuuk','Pacific/Easter','Pacific/Efate',
'Pacific/Enderbury','Pacific/Fakaofo','Pacific/Fiji','Pacific/Funafuti','Pacific/Galapagos','Pacific/Gambier',
'Pacific/Guadalcanal','Pacific/Guam','Pacific/Honolulu','Pacific/Johnston','Pacific/Kanton','Pacific/Kiritimati',
'Pacific/Kosrae','Pacific/Kwajalein','Pacific/Majuro','Pacific/Marquesas','Pacific/Midway','Pacific/Nauru',
'Pacific/Niue','Pacific/Norfolk','Pacific/Noumea','Pacific/Pago_Pago','Pacific/Palau','Pacific/Pitcairn','Pacific/Pohnpei',
'Pacific/Ponape','Pacific/Port_Moresby','Pacific/Rarotonga','Pacific/Saipan','Pacific/Samoa','Pacific/Tahiti',
'Pacific/Tarawa','Pacific/Tongatapu','Pacific/Truk','Pacific/Wake','Pacific/Wallis','Pacific/Yap',

'US/Alaska','US/Aleutian','US/Arizona','US/Central','US/East-Indiana','US/Eastern','US/Hawaii','US/Indiana-Starke',
'US/Michigan','US/Mountain','US/Pacific','US/Samoa'
]

// language/locale tests
var gLocales = [
	// ISO_639-1 alpha-2 codes
	// https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
	//* not supported in FF
'aa,afar',
'ab,abkhazian',
'ae,avestan',
'an,aragonese',
'av,avaric',
'ay,aymara',
'ba,bashkir',
'bi,bislama',
'ch,chamorro',
'co,corsican',
'cr,cree',
'cu,church slavic',
'dv,divehi',
'fj,fijian',
'gn,guarani',
'ho,hiri motu',
'ht,haitian',
'hz,herero',
'ik,inupiaq',
'io,ido',
'iu,inuktitut',
'kg,kongo',
'kj,kuanyama',
'kr,kanuri',
'kv,komi',
'la,latin',
'li,limburgan',
'mh,marshallese',
'na,nauru',
'ng,ndonga',
'nr,south ndebele',
'nv,navajo',
'ny,chichewa',
'oj,ojibwa',
'pi,pali',
'sm,samoan',
'ss,siswati',
'st,southern sotho',
'tn,tswana',
'ts,tsonga',
'ty,tahitian',
've,venda',
'vo,volapük',
'wa,walloon',
	//*/

'af,afrikaans',
'ak,akan',
'am,amharic',
'ar,arabic',
'as,assamese',
'az,azerbaijani',
'be,belarusian',
'bg,bulgarian',
'bm,bambara',
'bn,bengali',
'bo,tibetan',
'br,breton',
'bs,bosnian',
'ca,catalan',
'ce,chechen',
'cs,czech',
'cv,chuvash',
'cy,welsh',
'da,danish',
'de,german',
'dz,dzongkha',
'ee,éwé',
'el,greek',
'en,english',
'eo,esperanto',
'es,spanish',
'et,estonian',
'eu,basque',
'fa,persian',
'ff,fulah',
'fi,finnish',
'fo,faroese',
'fr,french',
'fy,frisian',
'ga,irish',
'gd,scottish gaelic',
'gl,galician',
'gu,gujarati',
'gv,manx',
'ha,hausa',
'he,hebrew',
'hi,hindi',
'hr,croatian',
'hu,hungarian',
'hy,armenian',
'ia,interlingua',
'id,indonesian',
'ie,interlingue',
'ig,igbo',
'ii,sichuan yi',
'is,icelandic',
'it,italian',
'ja,japanese',
'jv,javanese',
'ka,georgian',
'ki,kikuyu',
'kk,kazakh',
'kl,greenlandic',
'km,khmer',
'kn,kannada',
'ko,korean',
'ks,kashmiri',
'ku,kurdish',
'kw,cornish',
'ky,kyrgyz',
'lb,luxembourgish',
'lg,ganda',
'ln,lingala',
'lo,lao',
'lt,lithuanian',
'lu,luba-katanga',
'lv,latvian',
'mg,malagasy',
'mi,maori',
'mk,macedonian',
'ml,malayalam',
'mn,mongolian',
'mr,marathi',
'ms,malay',
'mt,maltese',
'my,burmese',
'nb,norwegian bokmål',
'nd,north ndebele',
'ne,nepali',
'nl,dutch',
'nn,norwegian nynorsk',
'no,norwegian',
'oc,occitan',
'om,oromo',
'or,odia',
'os,ossetian',
'pa,punjabi',
'pl,polish',
'ps,pashto',
'pt,portuguese',
'qu,quechua',
'rm,rhaeto-romanic',
'rn,kirundi',
'ro,romanian',
'ru,russian',
'rw,kinyarwanda',
'sa,sanskrit',
'sc,sardinian',
'sd,sindhi',
'se,northern sami',
'sg,sango',
'si,sinhala',
'sk,slovak',
'sl,slovenian',
'sn,shona',
'so,somali',
'sq,albanian',
'sr,serbian',
'su,sundanese',
'sv,swedish',
'sw,swahili',
'ta,tamil',
'te,telugu',
'tg,tajik',
'th,thai',
'ti,tigrinya',
'tk,turkmen',
'tl,tagalog',
'to,tongan',
'tr,turkish',
'tt,tatar',
'tw,twi',
'ug,uighur',
'uk,ukrainian',
'ur,urdu',
'uz,uzbek',
'vi,vietnamese',
'wo,wolof',
'xh,xhosa',
'yi,yiddish',
'yo,yoruba',
'za,zhuang',
'zh,chinese',
'zu,zulu',

	// ISO_639-2 alph-3 codes
	// https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
	// only add the ones supported in FF
'ast,asturian',
'bas,basaa',
'bem,bemba',
'bho,bhojpuri',
'ceb,cebuano',
'chr,cherokee',
'doi,dogri',
'dsb,lower sorbian',
'dua,duala',
'ewo,ewondo',
'fil,filipino',
'fur,friulian',
'gsw,swiss german',
'haw,hawaiian',
'hsb,upper sorbian',
'kab,kabyle',
'kam,kamba',
'kok,konkani',
'luo,luo',
'mai,maithili',
'mas,maasai',
'mni,meitei',
'nyn,nyankole',
'raj,rajasthani',
'sah,yakut',
'sat,santali', // 1731528, 1852843
'sco,scots', // 1714293
'smn,inari sámi',
'vai,vai',
'zgh,standard moroccan tamazight',

	// other alpha-3
'agq,aghem',
'asa,asu',
'bcg,haryanvi',
'bez,bena',
'bgc,haryanvi',
'blo,anii',
'brx,bodo',
'cak,kaqchikel',
'ccp,chakma',
'cgg,chiga',
'cho,choctaw',
'ckb,central kurdish',
'csw,swampy',
'dav,taita',
'dje,zarma',
'dyo,jola-fonyi',
'ebu,embu',
'gaa,ga',
'guz,gusii',
'jgo,ngomba',
'jmc,machame',
'kde,makonde',
'kea,kabuverdianu',
'kgp,kaingang',
'khq,koyra chiini',
'kkj,kako',
'kln,kalenjin',
'ksb,shambala',
'ksf,bafia',
'ksh,colognian',
'kxv,kuvi',
'lag,langi',
'lij,ligurian',
'lkt,lakota',
'lmo,lombard',
'lrc,northern luri',
'nso,northern sotho',
'ltg,latgalian',
'luy,luyia',
//'meh,mixtec (southwestern tlaxiaco)',
'mer,meru',
'mfe,morisyen',
'mgh,makhuwa-meetto',
'mgo,meta\'',
'mix,mixtepec mixtec',
'mua,mundang',
'mzn,mazanderani',
'naq,nama',
'nds,low german',
'nmg,kwasio',
'nnh,ngiemboon',
'nqo,n’ko',
'nus,nuer',
'pap,papiamento',
'pcm,nigerian',
'prg,prussian',
'rof,rombo',
'rwk,rwa',
'saq,samburu',
'sbp,sangu',
'seh,sena',
'shi,tachelhit',
'skr,saraiki', // 1808127, 1900150
'ses,koyraboro senni',
'syr,syriac',
'szl,silesian', // 1691695
'teo,teso',
'tok,toki pona',
'trs,triqui', // 1583177
'twq,tasawaq',
'tzm,central atlas tamazight',
'vec,venetian',
'vmw,makhuwa',
'vun,vunjo',
'wae,walser',
'xnr,kangri',
'xog,soga',
'yav,yangben',
'yue,cantonese',
'yrl,nhengatu',
'zh-cn,chinese (china)',
'zh-hans,chinese (simplified)',
'zh-hant,chinese (traditional)',
'zh-hk,chinese (hong kong)',
'zh-sg,chinese (singapore)',
'zh-tw,chinese (taiwan)',

/* ignore: maps to already listed items in expanded tests
'prs,dari', // fa-af
'sh,serbo-croatian', // sr-latn
'swc,congo', // sw-cd
//*/
]

// ** local files only for dev tests ** //
let gLocalesExpand = [
// the usual suspects
//*
'af-na,afrikaans (namibia)',
'ar-ae,arabic (united arabic emirates)',
'ar-bh,arabic (bahrain)',
'ar-dj,arabic (djibouti)',
'ar-dz,arabic (algeria)',
'ar-eg,arabic (egypt)',
'ar-er,arabic (eritrea)',
'ar-il,arabic (israel)',
'ar-iq,arabic (iraq)',
'ar-km,arabic (cosmoros)',
'ar-lb,arabic (lebanon)',
'ar-ly,arabic (libya)',
'ar-ma,arabic (morocco)',
'ar-mr,arabic (mauritania)',
'ar-sa,arabic (saudi arabia)',
'ar-so,arabic (somalia)',
'ar-ss,arabic (south sudan)',
'ar-tn,arabic (tunisia)',
'az-cyrl,azerbaijani (cyrillic)',
'bn-in,bengali (india)',
'bo-in,tibetan (india)',
'bs-cyrl,bosnian (cyrillic)',
'ca-fr,catalan (france)',
'ckb-ir,central kurdish (iran)',
'de-at,german (austria)',
'de-ch,german (switzerland)',
'de-li,german (liechtenstein)',
'de-lu,german (luxembourg)',
'dyo-sn,jola-fonyl (senegal)',
'ee-tg,éwé (togo)',
'en-001,english',
'en-150,english (europe)',
'en-ae,english (united arab emirates)',
'en-ag,english (antigua & barbuda)',
'en-ai,english (anguilla)',
'en-at,english (austria)',
'en-au,english (australia)',
'en-bb,english (barbados)',
'en-be,english (belgium)',
'en-bi,english (burundi)',
'en-bm,english (bermuda)',
'en-bs,english (bahamas)',
'en-bw,english (botswana)',
'en-bz,english (belize)',
'en-ca,english (canada)',
'en-cc,english (cocos islands)',
'en-ch,english (switzerland)',
'en-dk,english (denmark)',
'en-er,english (eritrea)',
'en-fi,english (finland)',
'en-fj,english (fiji)',
'en-fk,english (falkland islands)',
'en-gb,english (united kingdom)',
'en-gg,english (guernsey)',
'en-gh,english (ghana)',
'en-gi,english (gibraltar)',
'en-gm,english (gambia)',
'en-gu,english (guam)',
'en-gy,english (guyana)',
'en-hk,english (hong kong)',
'en-ie,english (ireland)',
'en-il,english (israel)',
'en-in,english (india)',
'en-jm,english (jamaica)',
'en-ke,english (kenya)',
'en-ky,english (cayman islands)',
'en-lr,english (liberia)',
'en-ls,english (lesotho)',
'en-mg,english (madagascar)',
'en-mh,english (marshall islands)',
'en-mo,english (macau)',
'en-mt,english (malta)',
'en-mu,english (mauritius)',
'en-mw,english (malawai)',
'en-my,english (malaysia)',
'en-na,english (namibia)',
'en-ng,english (nigeria)',
'en-nz,english (new zealand)',
'en-pg,english (papua new guinea)',
'en-pk,english (pakistan)',
'en-pr,english (puerto rico)',
'en-rw,english (rwanda)',
'en-sb,english (solomon islands)',
'en-sc,english (seychelles)',
'en-se,english (sweden)',
'en-sg,english (singapore)',
'en-sh,english (saint helena)',
'en-sl,english (sierra leone)',
'en-ss,english (south sudan)',
'en-sx,english (sint maarten)',
'en-sz,english (swaziland)',
'en-to,english (tonga)',
'en-tt,english (trinidad & tobago)',
'en-tz,english (tanzania)',
'en-ug,english (uganda)',
'en-vu,english (vanuatu)',
'en-ws,english (samoa)',
'en-za,english (south africa)',
'en-zm,english (zambia)',
'en-zw,english (zimbabwe)',
'es-419,spanish (latin america and the caribbean)',
'es-ar,spanish (argentina)',
'es-bo,spanish (bolivia)',
'es-br,spanish (brazil)',
'es-bz,spanish (belize)',
'es-cl,spanish (chile)',
'es-co,spanish (colombia)',
'es-cr,spanish (costa rica)',
'es-cu,spanish (cuba)',
'es-do,spanish (dominican republic)',
'es-ec,spanish (ecuador)',
'es-gq,spanish (equatorial guinea)',
'es-gt,spanish (guatemala)',
'es-hn,spanish (honduras)',
'es-mx,spanish (mexico)',
'es-ni,spanish (nicaragua)',
'es-pa,spanish (panama)',
'es-pe,spanish (peru)',
'es-ph,spanish (philippines)',
'es-pr,spanish (puerto rico)',
'es-py,spanish (paraguay)',
'es-sv,spanish (el salvador)',
'es-us,spanish (united states)',
'es-uy,spanish (uruguay)',
'es-ve,spanish (venezuela)',
'fa-af,persian (afghanistan)',
'ff-adlm,fulah (adlam)',
'ff-adlm-bf,fulah (adlam burkina faso)',
'ff-adlm-gh,fulah (adlam ghana)',
'ff-adlm-gm,fulah (adlam gambia)',
'ff-adlm-lr,fulah (adlamd liberia)',
'ff-adlm-mr,fulah (adlam mauritania)',
'ff-adlm-ng,fulah (adlam nigeria)',
'ff-adlm-sl,fulah (adlam sierra leone)',
'ff-gh,fulah (ghana)',
'ff-gn,fulah (guinea)',
'ff-mr,fulah (mauritania)',
'fo-dk,faroese (denmark)',
'fr-be,french (belgium)',
'fr-bi,french (burundi)',
'fr-ca,french (canada)',
'fr-cd,french (congo kinshasa)',
'fr-ch,french (switzerland)',
'fr-cm,french (cameroon)',
'fr-dj,french (djibouti)',
'fr-dz,french (algeria)',
'fr-gf,french (french guiana)',
'fr-gn,french (guinea)',
'fr-gp,french (guadeloupe)',
'fr-ht,french (haiti)',
'fr-km,french (comoros)',
'fr-lu,french (luxembourg)',
'fr-ma,french (morocco)',
'fr-ml,french (mali)',
'fr-mg,french (madagascar)',
'fr-mr,french (mauritania)',
'fr-mu,french (mauritius)',
'fr-rw,french (rwanda)',
'fr-sc,french (seychelles)',
'fr-sn,french (senegal)',
'fr-sy,french (syria)',
'fr-tn,french (tunisia)',
'fr-vu,french (vanuatu)',
'ha-gh,hausa (ghana)',
'hi-latn,hindi (latin)',
'hr-ba,croatian (bosnia & herzegovina)',
'it-ch,italian (switzerland)',
'kea-cv,kabuverdianu (cape verde)',
'ko-kp,korean (north korea)',
'kok-latn,konkani (latin)',
'ks-deva,kashmiri (devanagari)',
'kxv-telu,kuvi (telugu)',
'ln-ao,lingala (angola)',
'lrc-iq,northern luri (iraq)',
'mas-tz,masia (tanzania)',
'ms-bn,malay (brunei)',
'ms-id,malay (indonesia)',
'ms-sg,malay (singapore)',
'ne-in,nepali (india)',
'nl-aw,dutch (aruba)',
'nl-be,dutch (belgium)',
'nl-bq,dutch (caribbean netherlands)',
'nl-cw,dutch (curaçao)',
'nl-sr,dutch (suriname)',
'om-ke,oromo (kenya)',
'os-ru,ossetian (russia)',
'pa-arab,punjabi (arabic)',
'pa-pk,punjabi (pakistan)',
'ps-pk,pashto (pakistan)',
'pt-ao,portuguese (angola)',
'pt-ch,portuguese (switzerland)',
'pt-cv,portuguese (cape verde)',
'pt-gw,portuguese (guinea-bissau)',
'pt-lu,portuguese (luxembourg)',
'pt-mo,portuguese (macau)',
'pt-mz,portuguese (mazambique)',
'pt-pt,portuguese (portugal)',
'pt-st,portuguese (são tomé & príncipe)',
'qu-bo,quechua (bolivia)',
'qu-ec,quechua (ecuador)',
'ro-md,romanian (moldova)',
'ru-by,russian (belarus)',
'ru-kg,russian (kyrgyzstan)',
'ru-kz,russian (kazakhstan)',
'ru-md,russian (moldova)',
'ru-ua,russian (ukraine)',
'sd-deva,sindhi (devanagari)',
'se-fi,northern sami (finland)',
'se-se,northern sami',
'shi-latn,tachelhit (latin)',
'so-dj,somali (djibouti)',
'so-et,somali (ethiopia)',
'so-ke,somali (kenya)',
'sq-mk,albanian (macedonia)',
'sr-ba,serbian (bosnia & herzegovina)',
'sr-cyrl-ba,serbian (cyrillic bosnia & herzegovina)',
'sr-cyrl-me,serbian (cyrillic montenegro)',
'sr-cyrl-xk,serbian (cyrillic kosovo)',
'sr-latn,serbian (latin)',
'sr-latn-ba,serbian (latin bosnia & herzegovina)',
'sr-latn-me,serbian (latin montenegro)',
'sr-latn-xk,serbian (latin kosovo)',
'sr-me,serbian (montenegro)',
'sr-xk,serbian (kosovo)',
'st-ls,southern sotho',
'sv-fi,swedish (finland)',
'sw-cd,swahili (congo kinshasa)',
'sw-ke,swahili (kenya)',
'sw-ug,swahili (uganda)',
'ta-lk,tamil (sri lanka)',
'ta-my,tamil (malaysia)',
'ta-sg,tamil (singapore)',
'teo-ke,teso (kenya)',
'ti-er,tigrinya (eritrea)',
'tn-bw,tswana (botswana)',
'tr-cy,turkish (cyprus)',
'tr-tr,turkish (turkey)',
'ur-in,urdu (india)',
'uz-af,uzbek (afghanistan)',
'uz-arab,uzbek (arabic)',
'uz-cyrl-uz,uzbek (cyrillic uzbekistan)',
'vai-latn,vai (latin)',
'yo-bj,yoruba (benin)',
'yue-cn,cantonese (china)',
'yue-hans,cantonese (simplified)',
'zh-hans-hk,chinese (simplified hong kong)',
'zh-hans-mo,chinese (simplified macau)',
'zh-hant-mo,chinese (traditional macau)',
'zh-my,chinese (malaysia)',
//*/

// unlikely
//*
'af-arab,afrikaans (arabic)',
'af-brai,afrikaans (braille)',
'af-za,afrikaans (south africa)',
'agq-cm,aghem (cameroon)',
'ak-arab,akan (arabic)',
'ak-gh,akan (ghana)',
'ak-x-asante,akan',
'am-arab,amharic (arabic)',
'am-brai,amharic (braille)',
'am-et,amharic (ethiopic)',
'ar-001,arabic (world)',
'ar-brai,arabic (braille)',
'ar-eh,arabic (western sahara)',
'ar-jo,arabic (jordan)',
'ar-kw,arabic (kuwait)',
'ar-om,arabic (oman)',
'ar-ps,arabic (palestinian territories)',
'ar-qa,arabic (qatar)',
'ar-sd,arabic (sudan)',
'ar-sy,arabic (syria)',
'ar-syrc,arabic (syraic)',
'ar-td,arabic (chad)',
'ar-ye,arabic (yemen)',
'as-in,assamese (india)',
'asa-tz,asu (tanzania)',
'ast-es,asturian (spain)',
'az-brai,azerbaijani (braille)',
'az-cyrl-az,azerbaijani (cyrillic azerbaijan)',
'az-iq,azerbaijani (iraq)',
'az-ir,azerbaijani (iran)',
'az-latn,azerbaijani (latin)',
'az-ru,azerbaijani (russia)',
'bas-cm,basaa (cameroon)',
'be-arab,belarusian (arabic)',
'be-brai,belarusian (braille)',
'be-by,belarusian (belarus)',
'be-latn,belarusian',
'bem-brai,bemba (braille)',
'bem-zm,bemba (zambia)',
'bez-tz,bena (tanzania)',
'bg-bg,bulgarian (bulgaria)',
'bg-brai,bulgarian (braille)',
'bg-cyrs,bulgarian',
'bg-latn,bulgarian',
'bho-kthi,bhojpuri (kaithi)',
'bm-arab,bambara (arabic)',
'bm-ml,bambara (mali)',
'bm-nkoo,bambara',
'bn-bd,bengali (bangladesh)',
'bn-brai,bengali (braille)',
'bn-newa,bengali (newar)',
'bo-cn,tibetan (china)',
'bo-latn,tibetan',
'bo-marc,tibetan',
'bo-phag,tibetan',
'br-fr,breton (france)',
'br-ogam,breton',
'brx-beng,bodo (bengali)',
'brx-in,bodo (india)',
'brx-latn,bodo (latin)',
'bs-arab,bosnian (arabic)',
'bs-latn,bosnian (latin)',
'ca-ad,catalan (andorra)',
'ca-es,catalan (spain)',
'ca-it,catalan (italy)',
'ca-valencia,catalan (valencia)',
'ccp-bd,chakma (bangladesh)',
'ccp-beng,chakma (bengali)',
'ccp-in,chakma (india)',
'ccp-latn,chakma',
'ce-arab,chechen (arabic)',
'ce-latn,chechen',
'ce-ru,chechen (russia)',
'ceb-brai,cebuano (braille)',
'cgg-ug,chiga (uganda)',
'chr-latn,cherokee',
'chr-us,cherokee (united states)',
'ckb-iq,central kurdish (iraq)',
'ckb-latn,central kurdish',
'cs-brai,czech (braille)',
'cs-cz,czech (czechia)',
'cy-brai,welsh (braille)',
'cy-gb,welsh (united kingdom)',
'cy-ogam,welsh',
'da-brai,danish (braille)',
'da-dk,danish (denmark)',
'da-gl,danish (greenland)',
'da-runr,danish (runic)',
'dav-ke,taita (kenya)',
'de-be,german (belgium)',
'de-brai,german (braille)',
'de-de,german (germany)',
'de-dupl,german (duployan)',
'de-it,german (italy)',
'de-latf,german',
'de-runr,german (runic)',
'dje-arab,zarma (arabic)',
'dje-brai,zarma (braille)',
'dje-ne,zarma (niger)',
'doi-arab,dogri (arabic)',
'doi-dogr,dogri',
'doi-takr,dogri',
'dsb-de,lower sorbian (germany)',
'dua-cm,duala (cameroon)',
'dyo-arab,jola-fonyi (arabic)',
'dz-bt,dzongkha (bhutan)',
'ebu-ke,embu (kenya)',
'ee-brai,éwé (braille)',
'ee-gh,éwé (ghana)',
'el-brai,greek (braille)',
'el-cy,greek (cyprus)',
'el-cyrl,greek (cyrillic)',
'el-gr,greek (greece)',
'en-as,english (american samoa)',
'en-brai,english (braille)',
'en-ck,english (cook islands)',
'en-cm,english (cameroon)',
'en-cx,english (christmas island)',
'en-cy,english (cyprus)',
'en-de,english (germany)',
'en-dg,english (diego garcia)',
'en-dm,english (dominica)',
'en-dsrt,english (deseret)',
'en-dupl,english (duployan)',
'en-es,english (spain)', // ICU77 CLDR47
'en-fm,english (micronesia)',
'en-gd,english (grenada)',
'en-im,english (isle of man)',
'en-io,english (british indian oceam territory)',
'en-je,english (jersey)',
'en-ki,english (kiribati)',
'en-kn,english (saint kitts & nevis)',
'en-lc,english (saint lucia)',
'en-ma,english (morocco)',
'en-mp,english (northern mariana islands)',
'en-ms,english (montserrat)',
'en-nf,english (norfolk island)',
'en-nl,english (netherlands)',
'en-nr,english (nauru)',
'en-nu,english (niue)',
'en-ph,english (philippines)',
'en-pn,english (pitcarin islands)',
'en-pw,english (palau)',
'en-runr,english (runic)',
'en-sd,english (sudan)',
'en-shaw,english (shaw)',
'en-si,english (solvenia)',
'en-tc,english (turks & caicos islands)',
'en-tk,english (tokelau)',
'en-tv,english (tuvalu)',
'en-um,english (us outlying islands)',
'en-us,english (united states)',
'en-vc,english (saint vincent & grenadines)',
'en-vg,english (british virgin islands)',
'en-vi,english (us virgin islands)',
'es-brai,spanish (braille)',
'es-dupl,spanish (duployan)',
'es-ea,spanish (ceuta & melilla)',
'es-es,spanish (spain)',
'es-ic,spanish (canary islands)',
'et-brai,estonian (braille)',
'et-ee,estonian (estonia)',
'eu-es,basque (spain)',
'ewo-cm,ewondo (cameroon)',
'fa-ir,persian (iran)',
'ff-adlm-cm,fulah (adlam cameroon)',
'ff-adlm-gw,fulah (adlam guinea-bissau)',
'ff-adlm-ne,fulah (adlam niger)',
'ff-adlm-sn,fulah (adlam senegal)',
'ff-arab,fulah (arabic)',
'ff-bf,fulah (burkina faso)',
'ff-cm,fulah (cameroon)',
'ff-gm,fulah (gambia)',
'ff-gw,fulah (guinea-bissau)',
'ff-lr,fulah (liberia)',
'ff-ne,fulah (niger)',
'ff-ng,fulah (nigeria)',
'ff-sl,fulah (sierra leone)',
'ff-sn,fulah (senegal)',
'fi-brai,finnish (braille)',
'fi-fi,finnish (finland)',
'fil-ph,filipino (philippines)',
'fil-brai,filipino (braille)',
'fil-buhd,filipino',
'fil-hano,filipino',
'fil-tglg,filipino (tagalog)',
'fo-fo,faroese (faroe islands)',
'fo-runr,faroese (runic)',
'fr-bf,french (burkina faso)',
'fr-bj,french (benin)',
'fr-bl,french (saint barthélemy)',
'fr-brai,french (braille)',
'fr-cf,french (central african republic)',
'fr-cg,french (congo brazzaville)',
'fr-ci,french (côte d’ivoire)',
'fr-dupl,french (duployan)',
'fr-fr,french (france)',
'fr-ga,french (gabon)',
'fr-gq,french (equatorial guinea)',
'fr-mc,french (monaco)',
'fr-mf,french (saint martin)',
'fr-mq,french (martinique)',
'fr-nc,french (new caledonia)',
'fr-ne,french (niger)',
'fr-pf,french (french polynesia)',
'fr-pm,french (saint pierre & miquelon)',
'fr-re,french (réunion)',
'fr-td,french (chad)',
'fr-tg,french (togo)',
'fr-wf,french (wallis & futuna)',
'fr-yt,french (mayotte)',
'fur-it,friulian (italy)',
'fy-nl,frisian (netherlands)',
'ga-ie,irish (ireland)',
'ga-latg,irish',
'ga-ogam,irish',
'gd-gb,scottish gaelic (united kingdom)',
'gd-ogam,scottish gaelic',
'gl-es,galician (spain)',
'gsw-ch,swiss german (switzerland)',
'gsw-fr,swiss german (france)',
'gsw-li,swiss german (liechtenstein)',
'gu-brai,gujarati (braille)',
'gu-in,gujarati (india)',
'gu-khoj,gujarati',
'gv-im,manx (isle of man)',
'gv-ogam,manx',
'ha-arab,hausa (arabic)',
'ha-brai,hausa (braille)',
'ha-cm,hausa (cameroon)',
'ha-latn-ne,hausa (latin niger)',
'ha-ne,hausa (niger)',
'ha-ng,hausa (nigeria)',
'ha-sd,hausa (sudan)',
'haw-us,hawaiian (united states)',
'he-brai,hebrew (braille)',
'he-il,hebrew (israel)',
'hi-brai,hindi (braille)',
'hi-in,hindi (india)',
'hi-mahj,hindi',
'hi-newa,hindi (newar)',
'hr-brai,croatian (braille)',
'hr-hr,croatian (croatia)',
'hsb-de,upper sorbian (germany)',
'hu-brai,hungarian (braille)',
'hu-hu,hungarian (hungary',
'hy-am,armenian (armenia)',
'hy-brai,armenian (braille)',
'id-arab,indonesian (arabic)',
'id-brai,indonesian (braille)',
'id-id,indonesian (indonesia)',
'ig-ng,igbo (niger)',
'ii-cn,sichuan yi (china)',
'ii-latn,sichuan yi (latin)',
'is-is,icelandic (iceland)',
'is-runr,icelandic (runic)',
'it-brai,italian (braille)',
'it-it,italian (italy)',
'it-sm,italian (san marino)',
'it-va,italian (vatican city)',
'ja-brai,japanese (braille)',
'ja-jp,japanese (japan)',
'ja-latn,japanese (latin)',
'jmc-tz,machame (tanzania)',
'jv-arab,javanese (arabic)',
'jv-java,javanese',
'ka-brai,georgian (braille)',
'ka-ge,georgian (georgia)',
'ka-geok,georgian',
'kab-arab,kabyle (arabic)',
'kab-dz,kabyle (algeria)',
'kab-tfng,amazigh (tifinagh)',
'kam-ke,kamba (kenya)',
'kde-tz,makonde (tanzania)',
'khq-ml,koyra chiini (mali)',
'ki-ke,kikuyu (kenya)',
'kk-af,kazakh (afghanistan)',
'kk-brai,kazakh (braille)',
'kk-cn,kazakh (china)',
'kk-ir,kazakh',
'kk-kz,kazakh (kazakhstan)',
'kk-latn,kazakh',
'kk-mn,kazakh',
'kkj-cm,kako (cameroon)',
'kkj-td,kako',
'kl-gl,greenlandic (greenland)',
'kln-ke,kalenjin (kenya)',
'km-kh,khmer (cambodia)',
'kn-brai,kannada (braille)',
'kn-in,kannada (india)',
'kn-nand,kannada',
'ko-brai,korean (braille)',
'ko-kr,korean (south korea)',
'ko-latn,korean (latin)',
'kok-in,konkani (india)',
'kok-knda,konkani (kannada)',
'ks-in,kashmiri (india)',
'ks-latn,kashmiri (latin)',
'ks-shrd,kashmiri',
'ksb-tz,shambala (tanzania)',
'ksf-cm,bafia (cameroon)',
'ksh-de,colognian (germany)',
'ku-arab,kurdish (arabic)',
'ku-arab-tr,kurdish (arabic)',
'ku-armn,kurdish',
'ku-cyrl,kurdish (cyrillic)',
'ku-cyrl-az,kurdish (azerbaijan)',
'ku-lb,kurdish (lebanon)',
'ku-yezi-ge,kurdish',
'kw-gb,cornish (united kingdom)',
'kw-ogam,cornish',
'ky-cn,kyrgyz (china)',
'ky-kg,kyrgyz (kyrgyzstan)',
'ky-tr,kyrgyz',
'lag-tz,langi (tanzania)',
'lb-lu,luxembourgish (luxembourg)',
'lg-arab,ganda (arabic)',
'lg-ug,ganda (uganda)',
'lkt-us,lakota (united states)',
'ln-cd,lingala (congo kinshasa)',
'ln-cf,lingala (central african republic)',
'ln-cg,lingala (congo brazzaville)',
'lo-la,lao (laos)',
'lrc-ir,northern luri (iran)',
'lt-latf,lithuanian',
'lt-lt,lithuanian (lithuania)',
'lu-cd,luba-katanga (congo kinshasa)',
'luo-ke,luo (kenya)',
'luy-ke,luyia (kenya)',
'lv-brai,latvian (braille)',
'lv-lv,latvian (latvia)',
'mai-kthi,maithili (kaithi)',
'mai-newa,maithili (newar)',
'mai-tirh,maithili (tirhuta)',
'mas-ke,masia (kenya)',
'mer-ke,meru (kenya)',
'mfe-mu,morisyen (mauritius)',
'mg-arab,malagasy (arabic)',
'mg-brai,malagasy (braille)',
'mg-mg,malagasy (madagascar)',
'mgh-mz,makhuwa-meetto (mozambique)',
'mgo-cm,meta\' (cameroon)',
'mk-brai,macedonian (braille)',
'mk-mk,macedonian (north macedonia)',
'ml-arab,malayalam (arabic)',
'ml-brai,malayalam (braille)',
'ml-in,malayalam (india)',
'mn-brai,mongolian (braille)',
'mn-cn,mongolian (china)',
'mn-mn,mongolian (mongolia)',
'mn-phag,mongolian',
'mn-phag-mn, halh',
'mn-tibt,mongolian',
'mni-brai,meitei (braille)',
'mni-mtei,meitei',
'mr-brai,marathi (braille)',
'mr-in,marathi (india)',
'mr-modi,marathi',
'ms-arab,malay (arabic)',
'ms-brai,malay (braille)',
'ms-cc,malay',
'ms-my,malay (malaysia)',
'mt-arab,maltese (arabic)',
'mt-brai,maltese (braille)',
'mt-mt,maltese (malta)',
'mua-cm,mundang (cameroon)',
'my-brai,burmese (braille)',
'my-mm,burmese (burma)',
'mzn-ir,mazanderani (iran)',
'naq-na,nama (namibia)',
'nb-no,norwegian bokmål (norway)',
'nb-sj,norwegian bokmål (svalbard & jan mayen)',
'nd-zw,north ndebele (zimbabwe)',
'ne-brai,nepali (braille)',
'ne-newa,nepali (newar)',
'ne-np,nepali (nepal)',
'nl-brai,dutch (braille)',
'nl-nl,dutch (netherlands)',
'nl-sx,dutch (sint maarten)',
'nmg-gq,kwasio',
'nn-no,norwegian nynorsk (norway',
'nnh-cm,ngiemboon (cameroon)',
'no-runr,norwegian (runic)',
'nus-sd,nuer (sudan)',
'nus-ss,nuer (south sudan)',
'nyn-ug,nyankole (uganda)',
'om-arab,oromo (arabic)',
'om-et,oromo (ethiopia)',
'om-ethi,oromo (ethiopic)',
'or-brai,odia (braille)',
'or-in,odia (india)',
'os-ge,ossetian (georgia)',
'os-geor,ossetian',
'os-latn,ossetian (latin)',
'pa-guru,punjabi (gurmukhi)',
'pa-in,punjabi (india)',
'pa-khoj,punjabi',
'pa-mahj,punjabi',
'pl-brai,polish (braille)',
'pl-pl,polish (poland)',
'pt-br,portuguese (brazil)',
'pt-brai,portuguese (braille)',
'pt-gq,portuguese (equatorial guinea)',
'pt-tl,portuguese (timor-leste)',
'qu-pe,quechua (peru)',
'raj-latn,rajasthani (latin)',
'rm-ch,rhaeto-romanic (switzerland)',
'rn-bi,kirundi (burundi)',
'rn-brai,rundi (braille)',
'ro-brai,romanian (braille)',
'ro-cyrl,romanian (cyrillic)',
'ro-cyrs,romanian',
'ro-dupl,romanian (duployan)',
'ro-ro,romanian (romania)',
'rof-tz,rombo (tanzania)',
'ru-brai,russian (braille)',
'ru-ru,russian (russia)',
'rw-brai,kinyarwanda (braille)',
'rw-rw,kinyarwanda (rwanda)',
'rwk-tz,rwa (tanzania)',
'sa-bhks,sanskrit',
'sa-gran,sanskrit',
'sa-kawi,sanskrit',
'sa-khar,sanskrit',
'sa-mymr,sanskrit',
'sa-nand,sanskrit',
'sa-newa,sanskrit',
'sa-shrd,sanskrit',
'sa-sidd,sanskrit',
'sa-sinh,sanskrit',
'sa-tirh,sanskrit (tirhuta)',
'sah-cyrs,yakut',
'sah-latn,yakut (latin)',
'sah-ru,yakut (russia)',
'saq-ke,samburu (kenya)',
'sat-beng,santali (bengali)',
'sat-deva,santali (devanagari)',
'sat-latn,santali (latin)',
'sat-orya,santali',
'sbp-tz,sangu (tanzania)',
'sd-guru,sindhi',
'sd-khoj,sindhi',
'sd-khoj-pk,sindhi',
'sd-sind,sindhi',
'se-cyrl,northern sami (cyrillic)',
'se-no,northern sami (norway)',
'se-sw,northern sami (sweden)',
'seh-mz,sena (mozambique)',
'seh-x-podzu,sena',
'ses-ml,koyraboro senni (mali)',
'sg-cf,sango (central african republicj)',
'shi-arab,tachelhit (arabic)',
'shi-tfng,tachelhit (tifinagh)',
'si-brai,sinhala (braille)',
'si-lk,sinhala (sri lanka)',
'sk-brai,slovak (braille)',
'sk-sk,slovak (slovakia)',
'sl-brai,slovenian (braille)',
'sl-si,slovenian (slovenia)',
'smn-fi,inari sámi (finland)',
'sn-brai,shona (braille)',
'sn-zw,shona (zimbabwe)',
'so-arab,somali (arabic)',
'so-osma,somali',
'so-so,somali (somalia)',
'sq-al,albanian (albania)',
'sq-brai,albanian (braille)',
'sq-elba,albanian',
'sq-grek,albanian',
'sq-vith,albanian',
'sq-xk,albanian (kosovo)',
'sr-brai,serbian (braille)',
'sr-cyrl,serbian (cyrillic)',
'sr-ro,serbian',
'sr-ru,serbian',
'sr-tr,serbian',
'su-arab,sundanese (arabic)',
'su-java,sundanese',
'su-sund,sundanese',
'sv-ax,swedish (åland islands)',
'sv-brai,swedish (braille)',
'sv-runr,swedish (runic)',
'sv-se,swedish (sweden)',
'sw-arab,swahili (arabic)',
'sw-arab-cd,swahili (arabic congo kinshasa)',
'sw-brai,swahili (braille)',
'sw-tz,swahili (tanzania)',
'ta-arab,tamil (arabic)',
'ta-brai,tamil (braille)',
'ta-in,tamil (india)',
'te-brai,telugu (braille)',
'te-in,telugu (india)',
'teo-ug,teso (uganda)',
'tg-arab,tajik (arabic)',
'tg-hebr,tajik',
'tg-latn,tajik',
'tg-tj,tajik (tajikistan)',
'th-brai,thai (braille)',
'th-th,thai (thailand)',
'ti-arab,tigrinya (arabic)',
'ti-et,tigrinya (ethiopia)',
'tk-arab,turkmen (arabic)',
'tk-arab-ir,turkmen (arabic iran)',
'tk-cyrl,turkmen (cyrillic)',
'tl-brai,tagalog (braille)',
'tl-buhd,tagalog',
'tl-hano,tagalog',
'tl-tglg,tagalog (tagalog)',
'to-to,tongan (tonga)',
'tr-arab,turkish (arabic)',
'tr-brai,turkish (braille)',
'tr-cyrl,turkish (cyrillic)',
'tr-grek,turkish',
'tt-arab,tatar (arabic)',
'tt-latn,tatar (latin)',
'tt-ru,tatar (russia)',
'tw-x-asante,twi',
'twq-ne,tasawaq (niger)',
'tzm-arab,central atlas tamazight (arabic)',
'tzm-ma,central atlas tamazight (morocco)',
'tzm-tfng,central atlas tamazight (tifinagh)',
'ug-cn,uighur (china)',
'ug-kz,uyghur',
'ug-latn,uighur (latin)',
'ug-mn,uighur',
'uk-latn,ukrainian (latin)',
'uk-ua,ukrainian (ukraine)',
'ur-brai,urdu (braille)',
'ur-deva,urdu (devanagari)',
'ur-latn,urdu',
'ur-pk,urdu (pakistan)',
'uz-arab-af,uzbek (arabic afghanistan)',
'uz-brai,uzbek (braille)',
'uz-cn,uzbek (china)',
'uz-cryl,uzbek (cyrillic)',
'uz-latn,uzbek (latin)',
'uz-latn-uz,uzbek (latin uzbekistan)',
'uz-sogd,uzbek',
'vai-latn-lr,vai (latin liberia)',
'vai-vaii,vai (vai)',
'vai-vaii-lr,vai (vai liberia)',
'vi-brai,vietnamese (braille)',
'vi-hani,vietnamese',
'vi-vn,vietnamese (vietnam)',
'vi-x-central,vietnamese',
'vi-x-ncentral,vietnamese',
'vi-x-southern,vietnamese',
'vi-x-sub25,vietnamese',
'vi-x-sub31,vietnamese',
'vi-x-sub39,vietnamese',
'vi-x-sub49,vietnamese',
'vi-x-sub67,vietnamese',
'vi-x-subdn,vietnamese',
'vun-tz,vunjo (tanzania)',
'wae-ch,walser (switzerland)',
'wo-arab,wolof (arabic)',
'wo-sn,wolof (senegal)',
'xh-brai,xhosa (braille)',
'xog-ug,soga (uganda)',
'yav-cm,yangben (cameroon)',
'yi-001,yiddish (world)',
'yo-arab,yoruba (arabic)',
'yo-brai,yoruba (braille)',
'yo-ng,yoruba (nigeria)',
'yue-brai,cantonese (braille)',
'yue-hant,cantonese (traditional)',
'yue-hant-hk,cantonese (traditional hong kong)',
'yue-latn,yue (latin)',
'zgh-ma,standard moroccan tamazight (morocco)',
'zh-arab,chinese (arabic)',
'zh-au,chinese',
'zh-bn,chinese',
'zh-bopo,chinese',
'zh-brai,mandarin (braille)',
'zh-gb,chinese (united kingdom)',
'zh-gf,chinese',
'zh-hanb,chinese',
'zh-hans-cn,chinese (simplified china)',
'zh-hans-sg,chinese (simplified singapore)',
'zh-hant-hk,chinese (traditional hong kong)',
'zh-hant-tw,chinese (traditional taiwan)',
'zh-id,chinese (indonesia)',
'zh-latn,chinese (latin)',
'zh-mo,chinese (macau)',
'zh-pa,chinese (panama)',
'zh-pf,chinese',
'zh-ph,chinese (philippines)',
'zh-phag,chinese',
'zh-sr,chinese',
'zh-th,chinese',
'zh-us,chinese',
'zh-vn,chinese (vietnam)',
'zu-brai,zulu (braille)',
'zu-za,zulu (south africa)',
//*/

/* these map to already listed items
'arb-eg,arabic standard (egypt)', // ar-eg
'arb-lb,arabic standard (lebanon)', // ar-lb
'cnr,montenegrin', // sr-me
'cnr-latn,montenegrin', // sr-latn-me
'fil-tglg,filipino (tagalog)', // tl-tglg
'knn-knda,konkani (kannada)', // kok-knda
'knn-latn,konkani (latin)', // kok-latn
'swc-arab,congo (arabic)', // sw-arab-cd
'swh-arab,swahili (arabic)', // sw-arab
'swh-brai,swahili (braille)', // sw-brai
//*/
]

function expand_locales() {
 gLocales = gLocales.concat(gLocalesExpand)
}
// expand once in a while to see if entropy counts change
//expand_locales()

